import ast
import textwrap
import time
from typing import Dict, List


BANNED_NAMES = {
    "eval", "exec", "compile", "open", "input", "__import__", "globals", "locals",
    "vars", "dir", "getattr", "setattr", "delattr",
}
BANNED_ATTRS = {
    "system", "popen", "remove", "unlink", "rmdir", "rmtree", "rename", "replace",
    "kill", "terminate", "__dict__", "__class__", "__subclasses__",
}
ALLOWED_IMPORTS = {"shepherd_runtime"}


def _script_literal(value: str) -> str:
    return repr(str(value))


def _format_goto(step: Dict, indent: str = "        ") -> str:
    return (
        f"{indent}await drone.goto_location("
        f"lat={step['lat']}, lng={step['lng']}, alt={step.get('altitude_m', 10)}, "
        f"acceptance_radius_m={step.get('acceptance_radius_m', 3.0)})"
    )


def synthesize_action_script(program: Dict) -> Dict:
    compiled_program = program

    lines = [
        "# Generated by Shepherd-AI Tactical Compiler",
        "# Disposable mission script. Validated before MAVSDK/MAVLink dispatch.",
        "from shepherd_runtime import MissionContext, DroneAPI",
        "",
        "async def mission(api: DroneAPI, ctx: MissionContext):",
        f"    ctx.objective({_script_literal(program.get('source_prompt', ''))})",
        f"    ctx.compiler_pipeline({_script_literal(' -> '.join(program.get('compiler_pipeline', [])))})",
        "    async with ctx.safety_envelope(max_altitude_m=120, min_battery_percent=15):",
    ]

    for drone_program in compiled_program.get("drone_programs", []):
        drone_id = drone_program.get("drone_id")
        lines.append(f"        drone = api.drone({_script_literal(drone_id)})")
        for step in drone_program.get("steps", []):
            op = step.get("op")
            if op == "ARM":
                lines.append("        await drone.arm()")
            elif op == "TAKEOFF":
                lines.append(f"        await drone.takeoff(alt={step.get('altitude_m', 10)})")
            elif op == "GOTO":
                lines.append(_format_goto(step))
            elif op == "HOLD":
                lines.append(f"        await drone.hold(duration_s={step.get('duration_s', 1)})")
            elif op == "RTL":
                lines.append("        await drone.return_to_launch()")
            elif op == "LAND":
                lines.append("        await drone.land()")
        lines.append("")

    script = "\n".join(lines).rstrip() + "\n"
    sandbox = validate_action_script(script)
    return {
        "script_id": f"script-{program.get('mission_id', 'mission')}",
        "language": "Python Action Script / MAVSDK facade",
        "generated_at": time.time(),
        "script": script,
        "sandbox": sandbox,
        "sensor_events": [],
        "route_patches": [],
        "compiled_program": compiled_program,
    }


def validate_action_script(script: str) -> Dict:
    issues = []

    try:
        tree = ast.parse(script)
    except SyntaxError as exc:
        return {
            "safe": False,
            "passed": False,
            "issues": [f"syntax error: {exc}"],
            "checks": [],
        }

    checks = [
        "AST parsed successfully",
        "No filesystem/process/network primitives",
        "Only shepherd_runtime import allowed",
        "Altitude limits checked",
        "GPS coordinate bounds checked",
    ]

    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            module = node.module if isinstance(node, ast.ImportFrom) else node.names[0].name
            if module not in ALLOWED_IMPORTS:
                issues.append(f"blocked import: {module}")
        elif isinstance(node, ast.Name) and node.id in BANNED_NAMES:
            issues.append(f"blocked name: {node.id}")
        elif isinstance(node, ast.Attribute) and node.attr in BANNED_ATTRS:
            issues.append(f"blocked attribute: {node.attr}")
        elif isinstance(node, ast.Call):
            for keyword in node.keywords:
                if keyword.arg == "alt" and isinstance(keyword.value, ast.Constant):
                    if float(keyword.value.value) > 120:
                        issues.append("altitude exceeds 120m safety envelope")
                if keyword.arg in ("lat", "lng") and isinstance(keyword.value, ast.Constant):
                    value = float(keyword.value.value)
                    if keyword.arg == "lat" and not -90 <= value <= 90:
                        issues.append("latitude out of bounds")
                    if keyword.arg == "lng" and not -180 <= value <= 180:
                        issues.append("longitude out of bounds")

    return {
        "safe": len(issues) == 0,
        "passed": len(issues) == 0,
        "issues": issues,
        "checks": checks,
        "runtime_ms": 1,
        "note": "Script is statically validated; live drone dispatch still uses SHEPHERD-IR/MAVSDK constrained operations.",
    }
