apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shepherd-ai-539948
  namespace: aiea-interns
  labels:
    app.kubernetes.io/name: shepherd-ai
    shepherd-ai/study: multiuav-validation-placement-v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: rook-ceph-block
